### ISSUE TITLE
offloaded_doublevadd_publisher build is error out

### ISSUE THREAD

**Issue by surender009** [ros-acceleration/acceleration_examples#4] opened 2021-09-07 09:35 UTC
```bash
surender@xhdsurender41:/scratch/KRS/krs_ws$ colcon build --build-base=build-kv260 --install-base=install-kv260 --merge-install --mixin kv260 --packages-select ament_vitis ros2acceleration offloaded_doublevadd_publisher
Starting >>> ament_vitis
Starting >>> ros2acceleration
Finished <<< ament_vitis [0.60s]
Starting >>> offloaded_doublevadd_publisher
Finished <<< ros2acceleration [0.77s]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
--- stderr: offloaded_doublevadd_publisher
ERROR: The following input file does not exist: /scratch/KRS/krs_ws/build-kv260/offloaded_doublevadd_publisher/vadd.xclbin
---
Finished <<< offloaded_doublevadd_publisher [6min 21s]

Summary: 3 packages finished [6min 22s]
  1 package had stderr output: offloaded_doublevadd_publisher
surender@xhdsurender41:/scratch/KRS/krs_ws$
```

**Comment by vmayoral** [comment] 2021-09-08 08:10
@surender009 please use Markdown syntax to present your issues in a clear manner. I edited your request above for readibility.

Regarding the issue above, it seems to me like `vadd.xclbin` is not being created, and thereby, the CMake logic, fails to link it. Can you review the `v++` logs and/or paste them here for the `offloaded_doublevadd_publisher` package?

**Comment by vmayoral** [comment] 2021-09-08 08:40
@surender009 I just reproduced it in my machine and it worked just fine:

<details>

```bash
colcon build --build-base=build-kv260 --install-base=install-kv260 --merge-install --mixin kv260 --packages-select ament_vitis ros2acceleration offloaded_doublevadd_publisher
Starting >>> ament_vitis
Starting >>> ros2acceleration
Finished <<< ament_vitis [0.52s]
Starting >>> offloaded_doublevadd_publisher
Finished <<< ros2acceleration [0.60s]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
[Processing: offloaded_doublevadd_publisher]
Finished <<< offloaded_doublevadd_publisher [13min 47s]

Summary: 3 packages finished [13min 48s]
```

</details>

My only guess is that you might be running out of memory or similar. Take a look at the logs of the `v++` compiler, as indicated above.

**Comment by vmayoral** [comment] 2021-10-04 06:47
Closing since there're not further responses or comments.

**Closed by vmayoral** 2021-10-04 06:47 UTC
